#if !canImport(ObjectiveC)
import XCTest

extension UnstringifyFrameworkTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnstringifyFrameworkTests = [
        ("test", test),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(UnstringifyFrameworkTests.__allTests__UnstringifyFrameworkTests),
    ]
}
#endif
