#if !canImport(ObjectiveC)
import XCTest

extension FindStringsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FindStringsTests = [
        ("testUsage", testUsage)
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    [
        testCase(FindStringsTests.__allTests__FindStringsTests)
    ]
}
#endif
