#if !canImport(ObjectiveC)
import XCTest

extension UnstringifyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnstringifyTests = [
        ("testUsage", testUsage)
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    [
        testCase(UnstringifyTests.__allTests__UnstringifyTests)
    ]
}
#endif
