#if !canImport(ObjectiveC)
import XCTest

extension FindAndroidStringsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FindAndroidStringsTests = [
        ("testUsage", testUsage)
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    [
        testCase(FindAndroidStringsTests.__allTests__FindAndroidStringsTests)
    ]
}
#endif
