#if !canImport(ObjectiveC)
import XCTest

extension UnstringifiedTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnstringifiedTests = [
        ("testString", testString),
        ("testUppercased", testUppercased)
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    [
        testCase(UnstringifiedTests.__allTests__UnstringifiedTests)
    ]
}
#endif
